
```{r}
#################### Start User Input ####################

#Choose i/o type
samerows <- 1 #Set to 1 if input files same number of rows or 0 otherwise
phasesummary <- 1 #Set to 1 to summarize file by phase, or 0 to get all frames

#Set variables
root <- "2C_GR_M_" # root of the file name
sufix <- "_1_perflyborders" # sufix of file name
phasecol <- 1 # column with phases
columnpicker <- c(12) # column number(s) to combine
output <- c("RightCM_GR_M.csv") # output file names
flyrange <- 1:17 #

#################### End User Input ####################

#Load libraries
library(plyr)
library(tidyr)
library(dplyr)

#Define functions
estimate_mode <- function(x) {if (length(x)>1) {d<-density(na.omit(x)); d$x[which.max(d$y)]}else{x}}

#Pick wd
setwd(dirname(file.choose()))

#Get files
filenames <- list.files(path=getwd(), pattern=paste0(root, ".*", sufix, ".csv"))
mins <- read.csv(filenames[1], header = FALSE)[phasecol]
names(mins) <- "Min"

for (i in 1:NROW(columnpicker)) {
cols <- rep("NULL", NCOL(read.csv(filenames[1], header = FALSE)))

if (samerows==1) {
cols[c(columnpicker[i])] <- "numeric"
df <- do.call("cbind", lapply(filenames[flyrange],
                              read.table,
                              sep=",",
                              dec = ".",
                              header=FALSE,
                              na.string="NaN",
                              colClasses = cols)) %>%
    cbind(mins, .)
names(df) <- c("Min", paste0("Fly_", as.character(1:NROW(filenames[flyrange]))))
} else {
cols[c(phasecol, columnpicker[i])] <- "numeric"

df <- lapply(filenames[flyrange],
            read.table,
            sep=",",
            dec = ".",
            header=FALSE,
            na.string="NaN",
            colClasses = cols) %>%
  mapply(cbind, ., "Fly"=paste0("Fly_", as.character(1:NROW(filenames[flyrange]))), SIMPLIFY=F) %>%
  do.call("rbind", .) %>%
  mutate(id=row.names(.))
names(df) <- c("Val", "Min", "Fly", "id")
df <- spread(df, Fly, Val) %>%
  select(-id)
}

if (phasesummary==1) {
df <- group_by(df, Min) %>%
  summarise_each(funs(mean(., na.rm=TRUE), median(., na.rm=TRUE), min(., na.rm=TRUE), max(., na.rm=TRUE),
                      count=sum(!is.na(.)), sum(., na.rm=TRUE)), -Min) %>%
  mutate_each(funs(cumsum=cumsum(.)), (NCOL(.)-NROW(filenames)+1):NCOL(.))
}

write.table(df, output[i], row.names = FALSE, col.names = TRUE, sep=",")
}
print("All Done")
```


# Leftover stuff I don't remember what it does

```{r Other Stuff}
# df2 <- cbind(mins, df) %>%
#   gather(Fly, X, -Min) %>%
#   mutate(Tile=ifelse(X<=259, "L", ifelse(X<520, "M", "R"))) %>%
#   group_by(Min, Fly, Tile) %>%
#   summarise(n=n()/30) %>%
#   mutate(TileMin=ifelse(Min %in% c(2, 5, 8, 12, 15, 18), "L", ifelse(Min %in% c(1, 4, 7, 10, 13, 16, 19), "M", "R"))) %>%
#   arrange(Tile, Fly, Min) %>%
#   filter(Tile==TileMin) %>%
#   select(-TileMin, -Tile) %>%
#   arrange(Min, Fly) %>%
#   spread(Fly, n)

# unite(Fly_Tile, Fly, Tile) %>%
# spread(Fly_Tile, n)

# write.table(df, "TimeInSafe.csv", row.names = FALSE, col.names = TRUE, sep=",")
```


