---
title: "Start Explorer"
author: "Andrea Soto Padilla"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: lumen
runtime: shiny
---

```{r global, include=FALSE}
if (!require(pacman)) install.packages("pacman")
pacman::p_load(plyr, dplyr, tidyr, DT, data.table, lubridate, ggplot2, flexdashboard, knitr)

# If you ge an error saying "'is_latex_output' is not an exported object from 'namespace:knitr'"
#update knitter with the line bellow
#install.packages('knitr', repos = c('http://rforge.net', 'http://cran.rstudio.org'), type = 'source')

wd <- "/Users/lilmonk/Documents/GitHub/analysis_tracking/MomEffect/Modelling/"  ##Change accordingly

setwd(wd)

filenames <- list.files(wd, pattern="*.csv") ## Keep in folder only the .csv files that are of interest
```

```{r load and massage data}
df <- lapply(filenames, function(x) {
 read.csv(x, stringsAsFactors = FALSE) %>%
    mutate(Min=row_number()) %>%
    gather(Mother, Speed, -phase, -Min) %>%
    mutate(Mother=gsub("X", "", Mother)) %>%
    rename(Temp=phase)
  })
names(df) <- filenames
df <- do.call("rbind", df) %>%
  mutate(Name=row.names(.),
         Name=gsub("\\..*", "", Name)) %>%
  separate(Name, c("Experiment", "Sex", "Condition"), "_") %>%
  filter(!is.na(Speed)) %>%
  arrange(Experiment, Condition, Mother, Sex, Min, Temp)
```

```{r function list}
# Error function
erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1

# Quadratic
model_quad <- function(Temp, a, b, c) {
  (a*Temp^2) + (b*Temp) + c
}

# Gaussian
model_gauss <- function(Temp, a, b, c) {
  a*exp(-0.5*(abs(Temp-b)/c)^2)
}

# Skewed Gaussian
model_skewedgauss <- function(Temp, a, b, c, d) {
  a*exp(-0.5*(abs(Temp-b)/c)^2)*(1 + erf((d*(Temp-b))/(sqrt(2)*c)))
}

# Modified Gaussian
model_modgauss <- function(Temp, a, b, c, d) {
  a*exp(-0.5*(abs(Temp-b)/c)^d)
}

# Exponentially modified Gaussian
model_expgauss <- function(Temp, a, b, c, d) {
  ((a*c*sqrt(2*pi))/2*d)*exp( ((b-Temp)/d) + ((c^2)/(2*d^2)) )*( sign(d) - erf( ((b-Temp)/sqrt(2*c)) + (c/sqrt(2*d)) ) )
}

# Logan 6
model_logan6 <- function(Temp, psi, rho, dt, tm) {
  tau <- (tm - Temp)/dt
  s <- psi*(exp(rho*Temp) - exp((rho*tm)-tau))
  return(s)
}

# Logan 10
model_logan10 <- function(Temp, alpha, k, rho, dt, tm) {
  tau <- (tm - Temp)/dt
  s <- alpha*(((1 + k*exp(-rho*Temp))^(-1)) - exp(-tau))
  return(s)
}
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}

wellPanel(
  selectInput("condition", label = "Condition:",
              choices = unique(df$Condition),
              multiple = TRUE),
  
  selectInput("sex", label = "Sex:",
              choices = unique(df$Sex),
              multiple = TRUE),
  
  selectInput("models", label = "Model:",
              choices = c("Quadratic", "Gaussian", "Skewed Gaussian", "Modified Gaussian",
                          "Exponential Gaussian", "Logan 6", "Logan 10"), selected = "Gaussian"),
  
  sliderInput("temp", label = "Temperature Range:",
              min = 0, max = 50, value = c(16, 46), step = 1)
  )

renderUI({
  if (input$models %in% c("Gaussian", "Quadratic", "Modified Gaussian", "Skewed Gaussian", "Exponential Gaussian"))
    numericInput("a", label = " a:",
                min = -50, max = 50, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Gaussian", "Quadratic", "Modified Gaussian", "Skewed Gaussian", "Exponential Gaussian"))
    numericInput("b", label = " b:",
                min = -50, max = 50, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Gaussian", "Quadratic", "Modified Gaussian", "Skewed Gaussian", "Exponential Gaussian"))
    numericInput("c", label = " c:",
                min = -100, max = 100, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Modified Gaussian", "Skewed Gaussian", "Exponential Gaussian"))
    numericInput("d", label = " d:",
                min = -50, max = 50, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Logan 6", "Logan 10"))
    numericInput("dt", label = " dt:",
                min = 0, max = 50, value = 8, step = 0.01)
  })

renderUI({
  if (input$models %in% c("Logan 6", "Logan 10"))
    numericInput("tm", label = " tm:",
                min = 0, max = 50, value = 46, step = 0.01)
  })

renderUI({
  if (input$models %in% c("Logan 6", "Logan 10"))
    numericInput("rho", label = " rho:",
                min = -10, max = 10, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Logan 6"))
    numericInput("psi", label = " psi:",
                min = -10, max = 10, value = 1, step = 0.0001)
  })

renderUI({
  if (input$models %in% c("Logan 10"))
    numericInput("alpha", label = " alpha:",
                min = -50, max = 50, value = 1, step = 0.001)
  })

renderUI({
  if (input$models %in% c("Logan 10"))
    numericInput("k", label = " k:",
                min = -10, max = 450, value = 1, step = 1)
  })

```

Column
-----------------------------------------------------------------------

```{r data}
df_model <- reactive({
  Temp <- input$temp[1]:input$temp[2]
  
  if (input$models=="Quadratic") {
    Speed=model_quad(Temp, input$a, input$b, input$c)
  } else if (input$models=="Gaussian") {
    Speed=model_gauss(Temp, input$a, input$b, input$c)
  }  else if (input$models=="Skewed Gaussian") {
    Speed=model_skewedgauss(Temp, input$a, input$b, input$c, input$d)
  } else if (input$models=="Modified Gaussian") {
    Speed=model_modgauss(Temp, input$a, input$b, input$c, input$d)
  } else if (input$models=="Exponential Gaussian") {
    Speed=model_expgauss(Temp, input$a, input$b, input$c, input$d)
  } else if (input$models=="Logan 6") {
    Speed= model_logan6(Temp, input$psi, input$rho, input$dt, input$tm)
  } else if (input$models=="Logan 10") {
    Speed=model_logan10(Temp, input$alpha, input$k, input$rho, input$dt, input$tm)
  }
  
  df <- data.frame(Temp=Temp, Speed=Speed)
  
  return(df)
})

df_data <- reactive({
  if (is.null(input$condition) & is.null(input$sex)) {
    df %>%
      group_by(Temp) %>%
      summarise(Speed=mean(Speed, na.rm = TRUE)) %>%
      ungroup() %>%
      mutate(Group="All")
  } else if (!is.null(input$condition) & is.null(input$sex)) {
    df %>%
      filter(Condition %in% input$condition) %>%
      group_by(Condition, Temp) %>%
      summarise(Speed=mean(Speed, na.rm = TRUE)) %>%
      ungroup() %>%
      rename(Group=Condition)
  } else if (is.null(input$condition) & !is.null(input$sex)) {
    df %>%
      filter(Sex %in% input$sex) %>%
      group_by(Sex, Temp) %>%
      summarise(Speed=mean(Speed, na.rm = TRUE)) %>%
      ungroup() %>%
      rename(Group=Sex)
  } else if (!is.null(input$condition) & !is.null(input$sex)) {
    df %>%
      filter(Condition %in% input$condition, Sex %in% input$sex) %>%
      group_by(Condition, Sex, Temp) %>%
      summarise(Speed=mean(Speed, na.rm = TRUE)) %>%
      unite("Group", c("Condition","Sex"), sep =" - ")
  }
})
```

```{r}
renderPlot({
  ggplot(df_model(), aes(x=Temp, y=Speed)) +
    geom_line() +
    geom_line(data=df_data(), aes(x=Temp, y=Speed, color=Group), alpha=0.5) +
    theme_bw() +
    labs(color="")
})
```
